In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5])
b= np.array((1,2,3,4,5))
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [9]:
a = np.array([1,2,3,4,5], dtype='i')
b = np.array((1,2,3,4,5), dtype='f')

In [10]:
print(a)
print(b)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [13]:
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(c.ndim)

2


In [24]:
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]])
print(d.ndim)
print(d.shape[0])

3
2


In [17]:
print(c[0][0])

1
